name: API Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      #- uses: actions/setup-go@v1
      #  with:
      #    go-version: "1.13.7"
      - run: npm install
      - run: docker-compose up -d
      - run: curl http://localhost:8080
      - run: npm test
