name: API Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install npm packages
        run: npm install
      - name: Lint JS files
        run: npm run lint
      - name: Start API server
        run: docker-compose up -d
      - name: Run API tests against server
        run: npm test
