name: API Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      #- uses: actions/setup-go@v1
      #  with:
      #    go-version: "1.13.7"
      - run: npm install
      - run: npx now -t ${{ secrets.NOW_TOKEN }} dev &
        env: # Or as an environment variable
          NOW_PROJECT_ID: ${{ secrets.NOW_PROJECT_ID }}
          NOW_ORG_ID: ${{ secrets.NOW_ORG_ID }}
      - run: curl http://localhost:3000/api/v1/
      - run: npm test
